package com.padc.shared.Util

const val sharePreferenceDoctor  = "doctor"
const val sharePreferencelogin  = "login"
const val sharePreferenceName  = "name"
const val sharePreferenceEmail  = "email"
const val sharePreferenceID  = "id"
const val sharePreferenceRequestID  = "req_id"
const val sharePreferenceDeviceID  = "device_token"
const val sharePreferenceDateOfBirth  = "dateofBirth"
const val sharePreferenceHeight  = "height"
const val sharePreferenceBloodType = "bloodType"
const val sharePreferenceComment  = "comment"
const val sharePreferenceImage  = "image"
const val sharePreferenceWeight  = "weight"
const val shareBloodPressure  = "blod_pressure"
const val sharePreferencePhoto  = "photo"
const val sharePreferenceGeneralQuestion  = "question"
const val sharePreferenceGender= "gender"
const val sharePreferenceBio = "Bio"
const val sharePreferenceAddress = "address"
const val sharePreferenceExperience = "experience"
const val sharePreferencePhoneNumber = "pno"
const val sharePreferenceDegree = "degree"
const val sharePreferenceSpeciality  = "specialityName"