package com.padc.shared.Util

const val sharePreferenceDoctor  = "doctor"
const val sharePreferenceName  = "name"
const val sharePreferenceEmail  = "email"
const val sharePreferenceID  = "id"
const val sharePreferenceRequestIDforPatient  = "req_id"
const val sharePreferenceDeviceID  = "device_token"
const val sharePreferenceDateOfBirth  = "dateofBirth"
const val sharePreferenceComment  = "comment"
const val sharePreferenceImage  = "image"
const val sharePreferencePhoto  = "photo"
const val sharePreferenceSpeciality  = "specialityName"
const val sharePreferenceRequestID = "req_id"



////////////Patient
const val sharePreferencePatient  = "patient"
const val sharePreferenceLoginStatus  = "login"
const val sharePreferencePatientName  = "name"
const val sharePreferencePatientEmail  = "email"
const val sharePreferencePatientID  = "id"
const val sharePreferencePatientDeviceID  = "device_token"
const val sharePreferencePatientDateOfBirth  = "dateofBirth"
const val sharePreferencePatientHeight  = "height"
const val sharePreferencePatientBloodType = "bloodType"
const val sharePreferencePatientComment  = "comment"
const val sharePreferenceRequestIDtwo  = "req_id"
const val sharePreferencePatientBodyWeight  = "weight"
const val sharePreferencePatientBloodPressure  = "blod_pressure"
const val sharePreferencePatientPhoto  = "photo"
const val sharePreferenceGeneralQuestion  = "question"


const val sharePreferencePatienttwo  = "patient"
const val sharePreferenceLoginStatustwo = "login"
const val sharePreferencePatientNametwo  = "name"
const val sharePreferencePatientEmailtwo  = "email"
const val sharePreferencePatientIDtwo  = "id"
const val sharePreferencePatientDeviceIDtwo  = "device_token"
const val sharePreferencePatientDateOfBirthtwo  = "dateofBirth"
const val sharePreferencePatientHeighttwo  = "height"
const val sharePreferencePatientBloodTypetwo = "bloodType"
const val sharePreferencePatientCommenttwo  = "comment"
const val sharePreferencePatientBodyWeighttwo  = "weight"
const val sharePreferencePatientBloodPressuretwo  = "blod_pressure"
const val sharePreferencePatientPhototwo  = "photo"
const val sharePreferenceGeneralQuestiontwo  = "question"
const val sharePreferenceallegicPressuretwo  = "allegic_medicine"